### ISSUE TITLE
Does not work with perl 5.27.8

### ISSUE THREAD

**Issue by eserte** [yanick/List-Lazy#3]
With perl 5.27.8 (more exactly: since v5.27.7-212-g894f226e51) the order of signatures and prototypes was swapped (see also perldelta in 5.27.8, section "Subroutine attribute and signature order"), causing your module to fail. Test log is quite long beginning with:
```
Array found where operator expected at /home/eserte/.cpan/build/2018012418/List-Lazy-0.3.0-2/blib/lib/List/Lazy.pm line 43, near "$$@)"
        (Missing operator before @)?)
"my" variable $step masks earlier declaration in same statement at /home/eserte/.cpan/build/2018012418/List-Lazy-0.3.0-2/blib/lib/List/Lazy.pm line 44.
syntax error at /home/eserte/.cpan/build/2018012418/List-Lazy-0.3.0-2/blib/lib/List/Lazy.pm line 36, near ") :"
Global symbol "$generator" requires explicit package name (did you forget to declare "my $generator"?) at /home/eserte/.cpan/build/2018012418/List-Lazy-0.3.0-2/blib/lib/List/Lazy.pm line 38.
Global symbol "$state" requires explicit package name (did you forget to declare "my $state"?) at /home/eserte/.cpan/build/2018012418/List-Lazy-0.3.0-2/blib/lib/List/Lazy.pm line 39.
...
```

There's probably no way to use signatures and attributes and maintain compatibility down to 5.22. So probably it's best to not use at all the new perl features, and stick to plain old signature-less functions (and postderef could be dropped, too).

**Comment by xsawyerx** [comment]
Unfortunately, this is the risk of using experimental features. Until we pin them down, you cannot trust them in production.

**Comment by yanick** [comment]
> There's probably no way to use signatures and attributes and maintain compatibility down to 5.22. 

Heh. Challenge accepted. ;-)

**Comment by jkeenan** [comment]
Relevant bug ticket in perl5 bug queue:  https://rt.perl.org/Ticket/Display.html?id=132760

**Comment by jkeenan** [comment]
I'm wondering whether List-Lazy will be revised before the release of perl-5.28.0 in May.  In preparation for that release, I have been testing a selected subset of CPAN distributions against monthly development releases in the perl-5.27.* series.  List-Lazy falls into that subset, but fails tests when I attempt to install it against perl-5.27.10 on FreeBSD-11.0 using ```cpanm``` as the installer.  Here is an excerpt from the ```build.log```:
```
    "Building and testing List-Lazy-0.3.0",
    "cp lib/List/Lazy.pm blib/lib/List/Lazy.pm",
    "PERL_DL_NONLAZY=1 \"/usr/home/jkeenan/prep528/testing/perl-5.27.10/bin/perl\" \"-MExtUtils::Comman
d::MM\" \"-MTest::Harness\" \"-e\" \"undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/
arch')\" t/*.t",
    "",
    "#   Failed test 'List/Lazy.pm loaded ok'",
    "#   at t/00-compile.t line 43.",
    "#          got: '65280'",
    "#     expected: '0'",
    "Subroutine attributes must come before the signature at /usr/home/jkeenan/prep528/testing/perl-5.2
7.10/.cpanm/work/1522707005.7795/List-Lazy-0.3.0/blib/lib/List/Lazy.pm line 36.",
    "Compilation failed in require at -e line 1.",
    "# Looks like you failed 1 test of 1.",
    "t/00-compile.t ......... ",
    "Dubious, test returned 1 (wstat 256, 0x100)",
    "Failed 1/1 subtests ",
```
As I read Dave Mitchell's Feb 27 2018 comment (https://rt.perl.org/Ticket/Display.html?id=132760#txn-1535860), Perl 5 blead is not going to be modified further on this, which means that the onus is now on CPAN maintainers to adjust their modules to be perl-5.28-compliant.

Would it be possible to provide an update on the status of this issue?

Thank you very much.
Jim Keenan

**Comment by yanick** [comment]
Yup. The bug is not a huge priority right now as there is still a wee bit of time before 5.28 hits the shelves, but it'll be fixed in time.

**Comment by yanick** [comment]
:tada:  \o/

**Comment by jkeenan** [comment]
Confirmed.
[YANICK.List-Lazy-0.3.1.log.txt](https://github.com/yanick/List-Lazy/files/1881250/YANICK.List-Lazy-0.3.1.log.txt)
